// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Anime is the predicate function for anime builders.
type Anime func(*sql.Selector)

// Schedule is the predicate function for schedule builders.
type Schedule func(*sql.Selector)

// UserRating is the predicate function for userrating builders.
type UserRating func(*sql.Selector)
