// Code generated by ent, DO NOT EDIT.

package userrating

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/seva/animevista/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldEQ(FieldUserID, v))
}

// AnimeID applies equality check predicate on the "anime_id" field. It's identical to AnimeIDEQ.
func AnimeID(v int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldEQ(FieldAnimeID, v))
}

// Rating applies equality check predicate on the "rating" field. It's identical to RatingEQ.
func Rating(v float64) predicate.UserRating {
	return predicate.UserRating(sql.FieldEQ(FieldRating, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldLTE(FieldUserID, v))
}

// AnimeIDEQ applies the EQ predicate on the "anime_id" field.
func AnimeIDEQ(v int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldEQ(FieldAnimeID, v))
}

// AnimeIDNEQ applies the NEQ predicate on the "anime_id" field.
func AnimeIDNEQ(v int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldNEQ(FieldAnimeID, v))
}

// AnimeIDIn applies the In predicate on the "anime_id" field.
func AnimeIDIn(vs ...int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldIn(FieldAnimeID, vs...))
}

// AnimeIDNotIn applies the NotIn predicate on the "anime_id" field.
func AnimeIDNotIn(vs ...int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldNotIn(FieldAnimeID, vs...))
}

// AnimeIDGT applies the GT predicate on the "anime_id" field.
func AnimeIDGT(v int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldGT(FieldAnimeID, v))
}

// AnimeIDGTE applies the GTE predicate on the "anime_id" field.
func AnimeIDGTE(v int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldGTE(FieldAnimeID, v))
}

// AnimeIDLT applies the LT predicate on the "anime_id" field.
func AnimeIDLT(v int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldLT(FieldAnimeID, v))
}

// AnimeIDLTE applies the LTE predicate on the "anime_id" field.
func AnimeIDLTE(v int64) predicate.UserRating {
	return predicate.UserRating(sql.FieldLTE(FieldAnimeID, v))
}

// RatingEQ applies the EQ predicate on the "rating" field.
func RatingEQ(v float64) predicate.UserRating {
	return predicate.UserRating(sql.FieldEQ(FieldRating, v))
}

// RatingNEQ applies the NEQ predicate on the "rating" field.
func RatingNEQ(v float64) predicate.UserRating {
	return predicate.UserRating(sql.FieldNEQ(FieldRating, v))
}

// RatingIn applies the In predicate on the "rating" field.
func RatingIn(vs ...float64) predicate.UserRating {
	return predicate.UserRating(sql.FieldIn(FieldRating, vs...))
}

// RatingNotIn applies the NotIn predicate on the "rating" field.
func RatingNotIn(vs ...float64) predicate.UserRating {
	return predicate.UserRating(sql.FieldNotIn(FieldRating, vs...))
}

// RatingGT applies the GT predicate on the "rating" field.
func RatingGT(v float64) predicate.UserRating {
	return predicate.UserRating(sql.FieldGT(FieldRating, v))
}

// RatingGTE applies the GTE predicate on the "rating" field.
func RatingGTE(v float64) predicate.UserRating {
	return predicate.UserRating(sql.FieldGTE(FieldRating, v))
}

// RatingLT applies the LT predicate on the "rating" field.
func RatingLT(v float64) predicate.UserRating {
	return predicate.UserRating(sql.FieldLT(FieldRating, v))
}

// RatingLTE applies the LTE predicate on the "rating" field.
func RatingLTE(v float64) predicate.UserRating {
	return predicate.UserRating(sql.FieldLTE(FieldRating, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserRating {
	return predicate.UserRating(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserRating) predicate.UserRating {
	return predicate.UserRating(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserRating) predicate.UserRating {
	return predicate.UserRating(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserRating) predicate.UserRating {
	return predicate.UserRating(sql.NotPredicates(p))
}
