CREATE TABLE IF NOT EXISTS titles (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code VARCHAR(64) UNIQUE NOT NULL,
  name_en VARCHAR(140) NOT NULL,
  name_ru VARCHAR(140),
  name_uk VARCHAR(140),
  color VARCHAR(32) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_titles (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  title_id BIGINT NOT NULL REFERENCES titles (id) ON DELETE CASCADE,
  assigned_by BIGINT REFERENCES users (id) ON DELETE SET NULL,
  assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, title_id)
);

CREATE INDEX IF NOT EXISTS idx_user_titles_user_id ON user_titles (user_id);
CREATE INDEX IF NOT EXISTS idx_user_titles_title_id ON user_titles (title_id);

