// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/seva/animevista/ent/anime"
)

// Anime is the model entity for the Anime schema.
type Anime struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Image holds the value of the "image" field.
	Image string `json:"image,omitempty"`
	// AverageRating holds the value of the "average_rating" field.
	AverageRating float64 `json:"average_rating,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AnimeQuery when eager-loading is set.
	Edges        AnimeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AnimeEdges holds the relations/edges for other nodes in the graph.
type AnimeEdges struct {
	// Schedules holds the value of the schedules edge.
	Schedules []*Schedule `json:"schedules,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SchedulesOrErr returns the Schedules value or an error if the edge
// was not loaded in eager-loading.
func (e AnimeEdges) SchedulesOrErr() ([]*Schedule, error) {
	if e.loadedTypes[0] {
		return e.Schedules, nil
	}
	return nil, &NotLoadedError{edge: "schedules"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Anime) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case anime.FieldAverageRating:
			values[i] = new(sql.NullFloat64)
		case anime.FieldID:
			values[i] = new(sql.NullInt64)
		case anime.FieldName, anime.FieldURL, anime.FieldImage:
			values[i] = new(sql.NullString)
		case anime.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Anime fields.
func (_m *Anime) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case anime.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case anime.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case anime.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case anime.FieldImage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image", values[i])
			} else if value.Valid {
				_m.Image = value.String
			}
		case anime.FieldAverageRating:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field average_rating", values[i])
			} else if value.Valid {
				_m.AverageRating = value.Float64
			}
		case anime.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Anime.
// This includes values selected through modifiers, order, etc.
func (_m *Anime) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySchedules queries the "schedules" edge of the Anime entity.
func (_m *Anime) QuerySchedules() *ScheduleQuery {
	return NewAnimeClient(_m.config).QuerySchedules(_m)
}

// Update returns a builder for updating this Anime.
// Note that you need to call Anime.Unwrap() before calling this method if this Anime
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Anime) Update() *AnimeUpdateOne {
	return NewAnimeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Anime entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Anime) Unwrap() *Anime {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Anime is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Anime) String() string {
	var builder strings.Builder
	builder.WriteString("Anime(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("image=")
	builder.WriteString(_m.Image)
	builder.WriteString(", ")
	builder.WriteString("average_rating=")
	builder.WriteString(fmt.Sprintf("%v", _m.AverageRating))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Animes is a parsable slice of Anime.
type Animes []*Anime
