// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/seva/animevista/ent/anime"
	"github.com/seva/animevista/ent/schedule"
)

// AnimeCreate is the builder for creating a Anime entity.
type AnimeCreate struct {
	config
	mutation *AnimeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *AnimeCreate) SetName(v string) *AnimeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *AnimeCreate) SetURL(v string) *AnimeCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetImage sets the "image" field.
func (_c *AnimeCreate) SetImage(v string) *AnimeCreate {
	_c.mutation.SetImage(v)
	return _c
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_c *AnimeCreate) SetNillableImage(v *string) *AnimeCreate {
	if v != nil {
		_c.SetImage(*v)
	}
	return _c
}

// SetAverageRating sets the "average_rating" field.
func (_c *AnimeCreate) SetAverageRating(v float64) *AnimeCreate {
	_c.mutation.SetAverageRating(v)
	return _c
}

// SetNillableAverageRating sets the "average_rating" field if the given value is not nil.
func (_c *AnimeCreate) SetNillableAverageRating(v *float64) *AnimeCreate {
	if v != nil {
		_c.SetAverageRating(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AnimeCreate) SetUpdatedAt(v time.Time) *AnimeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AnimeCreate) SetNillableUpdatedAt(v *time.Time) *AnimeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AnimeCreate) SetID(v int64) *AnimeCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddScheduleIDs adds the "schedules" edge to the Schedule entity by IDs.
func (_c *AnimeCreate) AddScheduleIDs(ids ...int64) *AnimeCreate {
	_c.mutation.AddScheduleIDs(ids...)
	return _c
}

// AddSchedules adds the "schedules" edges to the Schedule entity.
func (_c *AnimeCreate) AddSchedules(v ...*Schedule) *AnimeCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddScheduleIDs(ids...)
}

// Mutation returns the AnimeMutation object of the builder.
func (_c *AnimeCreate) Mutation() *AnimeMutation {
	return _c.mutation
}

// Save creates the Anime in the database.
func (_c *AnimeCreate) Save(ctx context.Context) (*Anime, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AnimeCreate) SaveX(ctx context.Context) *Anime {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnimeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnimeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AnimeCreate) defaults() {
	if _, ok := _c.mutation.AverageRating(); !ok {
		v := anime.DefaultAverageRating
		_c.mutation.SetAverageRating(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := anime.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AnimeCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Anime.name"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Anime.url"`)}
	}
	if _, ok := _c.mutation.AverageRating(); !ok {
		return &ValidationError{Name: "average_rating", err: errors.New(`ent: missing required field "Anime.average_rating"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Anime.updated_at"`)}
	}
	return nil
}

func (_c *AnimeCreate) sqlSave(ctx context.Context) (*Anime, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AnimeCreate) createSpec() (*Anime, *sqlgraph.CreateSpec) {
	var (
		_node = &Anime{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(anime.Table, sqlgraph.NewFieldSpec(anime.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(anime.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(anime.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Image(); ok {
		_spec.SetField(anime.FieldImage, field.TypeString, value)
		_node.Image = value
	}
	if value, ok := _c.mutation.AverageRating(); ok {
		_spec.SetField(anime.FieldAverageRating, field.TypeFloat64, value)
		_node.AverageRating = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(anime.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.SchedulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   anime.SchedulesTable,
			Columns: []string{anime.SchedulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(schedule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Anime.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AnimeUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *AnimeCreate) OnConflict(opts ...sql.ConflictOption) *AnimeUpsertOne {
	_c.conflict = opts
	return &AnimeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Anime.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AnimeCreate) OnConflictColumns(columns ...string) *AnimeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AnimeUpsertOne{
		create: _c,
	}
}

type (
	// AnimeUpsertOne is the builder for "upsert"-ing
	//  one Anime node.
	AnimeUpsertOne struct {
		create *AnimeCreate
	}

	// AnimeUpsert is the "OnConflict" setter.
	AnimeUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *AnimeUpsert) SetName(v string) *AnimeUpsert {
	u.Set(anime.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AnimeUpsert) UpdateName() *AnimeUpsert {
	u.SetExcluded(anime.FieldName)
	return u
}

// SetURL sets the "url" field.
func (u *AnimeUpsert) SetURL(v string) *AnimeUpsert {
	u.Set(anime.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *AnimeUpsert) UpdateURL() *AnimeUpsert {
	u.SetExcluded(anime.FieldURL)
	return u
}

// SetImage sets the "image" field.
func (u *AnimeUpsert) SetImage(v string) *AnimeUpsert {
	u.Set(anime.FieldImage, v)
	return u
}

// UpdateImage sets the "image" field to the value that was provided on create.
func (u *AnimeUpsert) UpdateImage() *AnimeUpsert {
	u.SetExcluded(anime.FieldImage)
	return u
}

// ClearImage clears the value of the "image" field.
func (u *AnimeUpsert) ClearImage() *AnimeUpsert {
	u.SetNull(anime.FieldImage)
	return u
}

// SetAverageRating sets the "average_rating" field.
func (u *AnimeUpsert) SetAverageRating(v float64) *AnimeUpsert {
	u.Set(anime.FieldAverageRating, v)
	return u
}

// UpdateAverageRating sets the "average_rating" field to the value that was provided on create.
func (u *AnimeUpsert) UpdateAverageRating() *AnimeUpsert {
	u.SetExcluded(anime.FieldAverageRating)
	return u
}

// AddAverageRating adds v to the "average_rating" field.
func (u *AnimeUpsert) AddAverageRating(v float64) *AnimeUpsert {
	u.Add(anime.FieldAverageRating, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AnimeUpsert) SetUpdatedAt(v time.Time) *AnimeUpsert {
	u.Set(anime.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AnimeUpsert) UpdateUpdatedAt() *AnimeUpsert {
	u.SetExcluded(anime.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Anime.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(anime.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AnimeUpsertOne) UpdateNewValues() *AnimeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(anime.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Anime.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AnimeUpsertOne) Ignore() *AnimeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AnimeUpsertOne) DoNothing() *AnimeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AnimeCreate.OnConflict
// documentation for more info.
func (u *AnimeUpsertOne) Update(set func(*AnimeUpsert)) *AnimeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AnimeUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *AnimeUpsertOne) SetName(v string) *AnimeUpsertOne {
	return u.Update(func(s *AnimeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AnimeUpsertOne) UpdateName() *AnimeUpsertOne {
	return u.Update(func(s *AnimeUpsert) {
		s.UpdateName()
	})
}

// SetURL sets the "url" field.
func (u *AnimeUpsertOne) SetURL(v string) *AnimeUpsertOne {
	return u.Update(func(s *AnimeUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *AnimeUpsertOne) UpdateURL() *AnimeUpsertOne {
	return u.Update(func(s *AnimeUpsert) {
		s.UpdateURL()
	})
}

// SetImage sets the "image" field.
func (u *AnimeUpsertOne) SetImage(v string) *AnimeUpsertOne {
	return u.Update(func(s *AnimeUpsert) {
		s.SetImage(v)
	})
}

// UpdateImage sets the "image" field to the value that was provided on create.
func (u *AnimeUpsertOne) UpdateImage() *AnimeUpsertOne {
	return u.Update(func(s *AnimeUpsert) {
		s.UpdateImage()
	})
}

// ClearImage clears the value of the "image" field.
func (u *AnimeUpsertOne) ClearImage() *AnimeUpsertOne {
	return u.Update(func(s *AnimeUpsert) {
		s.ClearImage()
	})
}

// SetAverageRating sets the "average_rating" field.
func (u *AnimeUpsertOne) SetAverageRating(v float64) *AnimeUpsertOne {
	return u.Update(func(s *AnimeUpsert) {
		s.SetAverageRating(v)
	})
}

// AddAverageRating adds v to the "average_rating" field.
func (u *AnimeUpsertOne) AddAverageRating(v float64) *AnimeUpsertOne {
	return u.Update(func(s *AnimeUpsert) {
		s.AddAverageRating(v)
	})
}

// UpdateAverageRating sets the "average_rating" field to the value that was provided on create.
func (u *AnimeUpsertOne) UpdateAverageRating() *AnimeUpsertOne {
	return u.Update(func(s *AnimeUpsert) {
		s.UpdateAverageRating()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AnimeUpsertOne) SetUpdatedAt(v time.Time) *AnimeUpsertOne {
	return u.Update(func(s *AnimeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AnimeUpsertOne) UpdateUpdatedAt() *AnimeUpsertOne {
	return u.Update(func(s *AnimeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AnimeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AnimeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AnimeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AnimeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AnimeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AnimeCreateBulk is the builder for creating many Anime entities in bulk.
type AnimeCreateBulk struct {
	config
	err      error
	builders []*AnimeCreate
	conflict []sql.ConflictOption
}

// Save creates the Anime entities in the database.
func (_c *AnimeCreateBulk) Save(ctx context.Context) ([]*Anime, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Anime, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnimeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AnimeCreateBulk) SaveX(ctx context.Context) []*Anime {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnimeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnimeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Anime.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AnimeUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *AnimeCreateBulk) OnConflict(opts ...sql.ConflictOption) *AnimeUpsertBulk {
	_c.conflict = opts
	return &AnimeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Anime.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AnimeCreateBulk) OnConflictColumns(columns ...string) *AnimeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AnimeUpsertBulk{
		create: _c,
	}
}

// AnimeUpsertBulk is the builder for "upsert"-ing
// a bulk of Anime nodes.
type AnimeUpsertBulk struct {
	create *AnimeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Anime.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(anime.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AnimeUpsertBulk) UpdateNewValues() *AnimeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(anime.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Anime.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AnimeUpsertBulk) Ignore() *AnimeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AnimeUpsertBulk) DoNothing() *AnimeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AnimeCreateBulk.OnConflict
// documentation for more info.
func (u *AnimeUpsertBulk) Update(set func(*AnimeUpsert)) *AnimeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AnimeUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *AnimeUpsertBulk) SetName(v string) *AnimeUpsertBulk {
	return u.Update(func(s *AnimeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AnimeUpsertBulk) UpdateName() *AnimeUpsertBulk {
	return u.Update(func(s *AnimeUpsert) {
		s.UpdateName()
	})
}

// SetURL sets the "url" field.
func (u *AnimeUpsertBulk) SetURL(v string) *AnimeUpsertBulk {
	return u.Update(func(s *AnimeUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *AnimeUpsertBulk) UpdateURL() *AnimeUpsertBulk {
	return u.Update(func(s *AnimeUpsert) {
		s.UpdateURL()
	})
}

// SetImage sets the "image" field.
func (u *AnimeUpsertBulk) SetImage(v string) *AnimeUpsertBulk {
	return u.Update(func(s *AnimeUpsert) {
		s.SetImage(v)
	})
}

// UpdateImage sets the "image" field to the value that was provided on create.
func (u *AnimeUpsertBulk) UpdateImage() *AnimeUpsertBulk {
	return u.Update(func(s *AnimeUpsert) {
		s.UpdateImage()
	})
}

// ClearImage clears the value of the "image" field.
func (u *AnimeUpsertBulk) ClearImage() *AnimeUpsertBulk {
	return u.Update(func(s *AnimeUpsert) {
		s.ClearImage()
	})
}

// SetAverageRating sets the "average_rating" field.
func (u *AnimeUpsertBulk) SetAverageRating(v float64) *AnimeUpsertBulk {
	return u.Update(func(s *AnimeUpsert) {
		s.SetAverageRating(v)
	})
}

// AddAverageRating adds v to the "average_rating" field.
func (u *AnimeUpsertBulk) AddAverageRating(v float64) *AnimeUpsertBulk {
	return u.Update(func(s *AnimeUpsert) {
		s.AddAverageRating(v)
	})
}

// UpdateAverageRating sets the "average_rating" field to the value that was provided on create.
func (u *AnimeUpsertBulk) UpdateAverageRating() *AnimeUpsertBulk {
	return u.Update(func(s *AnimeUpsert) {
		s.UpdateAverageRating()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AnimeUpsertBulk) SetUpdatedAt(v time.Time) *AnimeUpsertBulk {
	return u.Update(func(s *AnimeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AnimeUpsertBulk) UpdateUpdatedAt() *AnimeUpsertBulk {
	return u.Update(func(s *AnimeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AnimeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AnimeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AnimeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AnimeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
