// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/seva/animevista/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/seva/animevista/ent/anime"
	"github.com/seva/animevista/ent/schedule"
	"github.com/seva/animevista/ent/userrating"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Anime is the client for interacting with the Anime builders.
	Anime *AnimeClient
	// Schedule is the client for interacting with the Schedule builders.
	Schedule *ScheduleClient
	// UserRating is the client for interacting with the UserRating builders.
	UserRating *UserRatingClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Anime = NewAnimeClient(c.config)
	c.Schedule = NewScheduleClient(c.config)
	c.UserRating = NewUserRatingClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Anime:      NewAnimeClient(cfg),
		Schedule:   NewScheduleClient(cfg),
		UserRating: NewUserRatingClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Anime:      NewAnimeClient(cfg),
		Schedule:   NewScheduleClient(cfg),
		UserRating: NewUserRatingClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Anime.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Anime.Use(hooks...)
	c.Schedule.Use(hooks...)
	c.UserRating.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Anime.Intercept(interceptors...)
	c.Schedule.Intercept(interceptors...)
	c.UserRating.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AnimeMutation:
		return c.Anime.mutate(ctx, m)
	case *ScheduleMutation:
		return c.Schedule.mutate(ctx, m)
	case *UserRatingMutation:
		return c.UserRating.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AnimeClient is a client for the Anime schema.
type AnimeClient struct {
	config
}

// NewAnimeClient returns a client for the Anime from the given config.
func NewAnimeClient(c config) *AnimeClient {
	return &AnimeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `anime.Hooks(f(g(h())))`.
func (c *AnimeClient) Use(hooks ...Hook) {
	c.hooks.Anime = append(c.hooks.Anime, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `anime.Intercept(f(g(h())))`.
func (c *AnimeClient) Intercept(interceptors ...Interceptor) {
	c.inters.Anime = append(c.inters.Anime, interceptors...)
}

// Create returns a builder for creating a Anime entity.
func (c *AnimeClient) Create() *AnimeCreate {
	mutation := newAnimeMutation(c.config, OpCreate)
	return &AnimeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Anime entities.
func (c *AnimeClient) CreateBulk(builders ...*AnimeCreate) *AnimeCreateBulk {
	return &AnimeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AnimeClient) MapCreateBulk(slice any, setFunc func(*AnimeCreate, int)) *AnimeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AnimeCreateBulk{err: fmt.Errorf("calling to AnimeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AnimeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AnimeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Anime.
func (c *AnimeClient) Update() *AnimeUpdate {
	mutation := newAnimeMutation(c.config, OpUpdate)
	return &AnimeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AnimeClient) UpdateOne(_m *Anime) *AnimeUpdateOne {
	mutation := newAnimeMutation(c.config, OpUpdateOne, withAnime(_m))
	return &AnimeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AnimeClient) UpdateOneID(id int64) *AnimeUpdateOne {
	mutation := newAnimeMutation(c.config, OpUpdateOne, withAnimeID(id))
	return &AnimeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Anime.
func (c *AnimeClient) Delete() *AnimeDelete {
	mutation := newAnimeMutation(c.config, OpDelete)
	return &AnimeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AnimeClient) DeleteOne(_m *Anime) *AnimeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AnimeClient) DeleteOneID(id int64) *AnimeDeleteOne {
	builder := c.Delete().Where(anime.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AnimeDeleteOne{builder}
}

// Query returns a query builder for Anime.
func (c *AnimeClient) Query() *AnimeQuery {
	return &AnimeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAnime},
		inters: c.Interceptors(),
	}
}

// Get returns a Anime entity by its id.
func (c *AnimeClient) Get(ctx context.Context, id int64) (*Anime, error) {
	return c.Query().Where(anime.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AnimeClient) GetX(ctx context.Context, id int64) *Anime {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySchedules queries the schedules edge of a Anime.
func (c *AnimeClient) QuerySchedules(_m *Anime) *ScheduleQuery {
	query := (&ScheduleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(anime.Table, anime.FieldID, id),
			sqlgraph.To(schedule.Table, schedule.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, anime.SchedulesTable, anime.SchedulesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AnimeClient) Hooks() []Hook {
	return c.hooks.Anime
}

// Interceptors returns the client interceptors.
func (c *AnimeClient) Interceptors() []Interceptor {
	return c.inters.Anime
}

func (c *AnimeClient) mutate(ctx context.Context, m *AnimeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AnimeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AnimeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AnimeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AnimeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Anime mutation op: %q", m.Op())
	}
}

// ScheduleClient is a client for the Schedule schema.
type ScheduleClient struct {
	config
}

// NewScheduleClient returns a client for the Schedule from the given config.
func NewScheduleClient(c config) *ScheduleClient {
	return &ScheduleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `schedule.Hooks(f(g(h())))`.
func (c *ScheduleClient) Use(hooks ...Hook) {
	c.hooks.Schedule = append(c.hooks.Schedule, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `schedule.Intercept(f(g(h())))`.
func (c *ScheduleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Schedule = append(c.inters.Schedule, interceptors...)
}

// Create returns a builder for creating a Schedule entity.
func (c *ScheduleClient) Create() *ScheduleCreate {
	mutation := newScheduleMutation(c.config, OpCreate)
	return &ScheduleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Schedule entities.
func (c *ScheduleClient) CreateBulk(builders ...*ScheduleCreate) *ScheduleCreateBulk {
	return &ScheduleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ScheduleClient) MapCreateBulk(slice any, setFunc func(*ScheduleCreate, int)) *ScheduleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ScheduleCreateBulk{err: fmt.Errorf("calling to ScheduleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ScheduleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ScheduleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Schedule.
func (c *ScheduleClient) Update() *ScheduleUpdate {
	mutation := newScheduleMutation(c.config, OpUpdate)
	return &ScheduleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ScheduleClient) UpdateOne(_m *Schedule) *ScheduleUpdateOne {
	mutation := newScheduleMutation(c.config, OpUpdateOne, withSchedule(_m))
	return &ScheduleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ScheduleClient) UpdateOneID(id int64) *ScheduleUpdateOne {
	mutation := newScheduleMutation(c.config, OpUpdateOne, withScheduleID(id))
	return &ScheduleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Schedule.
func (c *ScheduleClient) Delete() *ScheduleDelete {
	mutation := newScheduleMutation(c.config, OpDelete)
	return &ScheduleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ScheduleClient) DeleteOne(_m *Schedule) *ScheduleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ScheduleClient) DeleteOneID(id int64) *ScheduleDeleteOne {
	builder := c.Delete().Where(schedule.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ScheduleDeleteOne{builder}
}

// Query returns a query builder for Schedule.
func (c *ScheduleClient) Query() *ScheduleQuery {
	return &ScheduleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSchedule},
		inters: c.Interceptors(),
	}
}

// Get returns a Schedule entity by its id.
func (c *ScheduleClient) Get(ctx context.Context, id int64) (*Schedule, error) {
	return c.Query().Where(schedule.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ScheduleClient) GetX(ctx context.Context, id int64) *Schedule {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAnime queries the anime edge of a Schedule.
func (c *ScheduleClient) QueryAnime(_m *Schedule) *AnimeQuery {
	query := (&AnimeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(schedule.Table, schedule.FieldID, id),
			sqlgraph.To(anime.Table, anime.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, schedule.AnimeTable, schedule.AnimeColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ScheduleClient) Hooks() []Hook {
	return c.hooks.Schedule
}

// Interceptors returns the client interceptors.
func (c *ScheduleClient) Interceptors() []Interceptor {
	return c.inters.Schedule
}

func (c *ScheduleClient) mutate(ctx context.Context, m *ScheduleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ScheduleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ScheduleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ScheduleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ScheduleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Schedule mutation op: %q", m.Op())
	}
}

// UserRatingClient is a client for the UserRating schema.
type UserRatingClient struct {
	config
}

// NewUserRatingClient returns a client for the UserRating from the given config.
func NewUserRatingClient(c config) *UserRatingClient {
	return &UserRatingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `userrating.Hooks(f(g(h())))`.
func (c *UserRatingClient) Use(hooks ...Hook) {
	c.hooks.UserRating = append(c.hooks.UserRating, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `userrating.Intercept(f(g(h())))`.
func (c *UserRatingClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserRating = append(c.inters.UserRating, interceptors...)
}

// Create returns a builder for creating a UserRating entity.
func (c *UserRatingClient) Create() *UserRatingCreate {
	mutation := newUserRatingMutation(c.config, OpCreate)
	return &UserRatingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserRating entities.
func (c *UserRatingClient) CreateBulk(builders ...*UserRatingCreate) *UserRatingCreateBulk {
	return &UserRatingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserRatingClient) MapCreateBulk(slice any, setFunc func(*UserRatingCreate, int)) *UserRatingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserRatingCreateBulk{err: fmt.Errorf("calling to UserRatingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserRatingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserRatingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserRating.
func (c *UserRatingClient) Update() *UserRatingUpdate {
	mutation := newUserRatingMutation(c.config, OpUpdate)
	return &UserRatingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserRatingClient) UpdateOne(_m *UserRating) *UserRatingUpdateOne {
	mutation := newUserRatingMutation(c.config, OpUpdateOne, withUserRating(_m))
	return &UserRatingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserRatingClient) UpdateOneID(id int64) *UserRatingUpdateOne {
	mutation := newUserRatingMutation(c.config, OpUpdateOne, withUserRatingID(id))
	return &UserRatingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserRating.
func (c *UserRatingClient) Delete() *UserRatingDelete {
	mutation := newUserRatingMutation(c.config, OpDelete)
	return &UserRatingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserRatingClient) DeleteOne(_m *UserRating) *UserRatingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserRatingClient) DeleteOneID(id int64) *UserRatingDeleteOne {
	builder := c.Delete().Where(userrating.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserRatingDeleteOne{builder}
}

// Query returns a query builder for UserRating.
func (c *UserRatingClient) Query() *UserRatingQuery {
	return &UserRatingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserRating},
		inters: c.Interceptors(),
	}
}

// Get returns a UserRating entity by its id.
func (c *UserRatingClient) Get(ctx context.Context, id int64) (*UserRating, error) {
	return c.Query().Where(userrating.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserRatingClient) GetX(ctx context.Context, id int64) *UserRating {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserRatingClient) Hooks() []Hook {
	return c.hooks.UserRating
}

// Interceptors returns the client interceptors.
func (c *UserRatingClient) Interceptors() []Interceptor {
	return c.inters.UserRating
}

func (c *UserRatingClient) mutate(ctx context.Context, m *UserRatingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserRatingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserRatingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserRatingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserRatingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserRating mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Anime, Schedule, UserRating []ent.Hook
	}
	inters struct {
		Anime, Schedule, UserRating []ent.Interceptor
	}
)
