// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/seva/animevista/ent/anime"
	"github.com/seva/animevista/ent/schedule"
	"github.com/seva/animevista/ent/schema"
	"github.com/seva/animevista/ent/userrating"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	animeFields := schema.Anime{}.Fields()
	_ = animeFields
	// animeDescAverageRating is the schema descriptor for average_rating field.
	animeDescAverageRating := animeFields[4].Descriptor()
	// anime.DefaultAverageRating holds the default value on creation for the average_rating field.
	anime.DefaultAverageRating = animeDescAverageRating.Default.(float64)
	// animeDescUpdatedAt is the schema descriptor for updated_at field.
	animeDescUpdatedAt := animeFields[5].Descriptor()
	// anime.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	anime.DefaultUpdatedAt = animeDescUpdatedAt.Default.(func() time.Time)
	// anime.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	anime.UpdateDefaultUpdatedAt = animeDescUpdatedAt.UpdateDefault.(func() time.Time)
	scheduleFields := schema.Schedule{}.Fields()
	_ = scheduleFields
	// scheduleDescCreatedAt is the schema descriptor for created_at field.
	scheduleDescCreatedAt := scheduleFields[4].Descriptor()
	// schedule.DefaultCreatedAt holds the default value on creation for the created_at field.
	schedule.DefaultCreatedAt = scheduleDescCreatedAt.Default.(func() time.Time)
	// scheduleDescUpdatedAt is the schema descriptor for updated_at field.
	scheduleDescUpdatedAt := scheduleFields[5].Descriptor()
	// schedule.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	schedule.DefaultUpdatedAt = scheduleDescUpdatedAt.Default.(func() time.Time)
	// schedule.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	schedule.UpdateDefaultUpdatedAt = scheduleDescUpdatedAt.UpdateDefault.(func() time.Time)
	userratingFields := schema.UserRating{}.Fields()
	_ = userratingFields
	// userratingDescRating is the schema descriptor for rating field.
	userratingDescRating := userratingFields[3].Descriptor()
	// userrating.RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	userrating.RatingValidator = func() func(float64) error {
		validators := userratingDescRating.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(rating float64) error {
			for _, fn := range fns {
				if err := fn(rating); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userratingDescCreatedAt is the schema descriptor for created_at field.
	userratingDescCreatedAt := userratingFields[4].Descriptor()
	// userrating.DefaultCreatedAt holds the default value on creation for the created_at field.
	userrating.DefaultCreatedAt = userratingDescCreatedAt.Default.(func() time.Time)
	// userratingDescUpdatedAt is the schema descriptor for updated_at field.
	userratingDescUpdatedAt := userratingFields[5].Descriptor()
	// userrating.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userrating.DefaultUpdatedAt = userratingDescUpdatedAt.Default.(func() time.Time)
	// userrating.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userrating.UpdateDefaultUpdatedAt = userratingDescUpdatedAt.UpdateDefault.(func() time.Time)
}
