// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/seva/animevista/ent/anime"
	"github.com/seva/animevista/ent/schedule"
)

// Schedule is the model entity for the Schedule schema.
type Schedule struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AnimeID holds the value of the "anime_id" field.
	AnimeID int64 `json:"anime_id,omitempty"`
	// ReleaseDatetime holds the value of the "release_datetime" field.
	ReleaseDatetime time.Time `json:"release_datetime,omitempty"`
	// EpisodeNumber holds the value of the "episode_number" field.
	EpisodeNumber int `json:"episode_number,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ScheduleQuery when eager-loading is set.
	Edges        ScheduleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ScheduleEdges holds the relations/edges for other nodes in the graph.
type ScheduleEdges struct {
	// Anime holds the value of the anime edge.
	Anime *Anime `json:"anime,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AnimeOrErr returns the Anime value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScheduleEdges) AnimeOrErr() (*Anime, error) {
	if e.Anime != nil {
		return e.Anime, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: anime.Label}
	}
	return nil, &NotLoadedError{edge: "anime"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Schedule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case schedule.FieldID, schedule.FieldAnimeID, schedule.FieldEpisodeNumber:
			values[i] = new(sql.NullInt64)
		case schedule.FieldReleaseDatetime, schedule.FieldCreatedAt, schedule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Schedule fields.
func (_m *Schedule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case schedule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case schedule.FieldAnimeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field anime_id", values[i])
			} else if value.Valid {
				_m.AnimeID = value.Int64
			}
		case schedule.FieldReleaseDatetime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field release_datetime", values[i])
			} else if value.Valid {
				_m.ReleaseDatetime = value.Time
			}
		case schedule.FieldEpisodeNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field episode_number", values[i])
			} else if value.Valid {
				_m.EpisodeNumber = int(value.Int64)
			}
		case schedule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case schedule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Schedule.
// This includes values selected through modifiers, order, etc.
func (_m *Schedule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAnime queries the "anime" edge of the Schedule entity.
func (_m *Schedule) QueryAnime() *AnimeQuery {
	return NewScheduleClient(_m.config).QueryAnime(_m)
}

// Update returns a builder for updating this Schedule.
// Note that you need to call Schedule.Unwrap() before calling this method if this Schedule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Schedule) Update() *ScheduleUpdateOne {
	return NewScheduleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Schedule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Schedule) Unwrap() *Schedule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Schedule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Schedule) String() string {
	var builder strings.Builder
	builder.WriteString("Schedule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("anime_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AnimeID))
	builder.WriteString(", ")
	builder.WriteString("release_datetime=")
	builder.WriteString(_m.ReleaseDatetime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("episode_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.EpisodeNumber))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Schedules is a parsable slice of Schedule.
type Schedules []*Schedule
