// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/seva/animevista/ent/anime"
	"github.com/seva/animevista/ent/schedule"
)

// ScheduleCreate is the builder for creating a Schedule entity.
type ScheduleCreate struct {
	config
	mutation *ScheduleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAnimeID sets the "anime_id" field.
func (_c *ScheduleCreate) SetAnimeID(v int64) *ScheduleCreate {
	_c.mutation.SetAnimeID(v)
	return _c
}

// SetReleaseDatetime sets the "release_datetime" field.
func (_c *ScheduleCreate) SetReleaseDatetime(v time.Time) *ScheduleCreate {
	_c.mutation.SetReleaseDatetime(v)
	return _c
}

// SetEpisodeNumber sets the "episode_number" field.
func (_c *ScheduleCreate) SetEpisodeNumber(v int) *ScheduleCreate {
	_c.mutation.SetEpisodeNumber(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ScheduleCreate) SetCreatedAt(v time.Time) *ScheduleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ScheduleCreate) SetNillableCreatedAt(v *time.Time) *ScheduleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ScheduleCreate) SetUpdatedAt(v time.Time) *ScheduleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ScheduleCreate) SetNillableUpdatedAt(v *time.Time) *ScheduleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ScheduleCreate) SetID(v int64) *ScheduleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetAnime sets the "anime" edge to the Anime entity.
func (_c *ScheduleCreate) SetAnime(v *Anime) *ScheduleCreate {
	return _c.SetAnimeID(v.ID)
}

// Mutation returns the ScheduleMutation object of the builder.
func (_c *ScheduleCreate) Mutation() *ScheduleMutation {
	return _c.mutation
}

// Save creates the Schedule in the database.
func (_c *ScheduleCreate) Save(ctx context.Context) (*Schedule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScheduleCreate) SaveX(ctx context.Context) *Schedule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScheduleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := schedule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := schedule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScheduleCreate) check() error {
	if _, ok := _c.mutation.AnimeID(); !ok {
		return &ValidationError{Name: "anime_id", err: errors.New(`ent: missing required field "Schedule.anime_id"`)}
	}
	if _, ok := _c.mutation.ReleaseDatetime(); !ok {
		return &ValidationError{Name: "release_datetime", err: errors.New(`ent: missing required field "Schedule.release_datetime"`)}
	}
	if _, ok := _c.mutation.EpisodeNumber(); !ok {
		return &ValidationError{Name: "episode_number", err: errors.New(`ent: missing required field "Schedule.episode_number"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Schedule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Schedule.updated_at"`)}
	}
	if len(_c.mutation.AnimeIDs()) == 0 {
		return &ValidationError{Name: "anime", err: errors.New(`ent: missing required edge "Schedule.anime"`)}
	}
	return nil
}

func (_c *ScheduleCreate) sqlSave(ctx context.Context) (*Schedule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScheduleCreate) createSpec() (*Schedule, *sqlgraph.CreateSpec) {
	var (
		_node = &Schedule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(schedule.Table, sqlgraph.NewFieldSpec(schedule.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ReleaseDatetime(); ok {
		_spec.SetField(schedule.FieldReleaseDatetime, field.TypeTime, value)
		_node.ReleaseDatetime = value
	}
	if value, ok := _c.mutation.EpisodeNumber(); ok {
		_spec.SetField(schedule.FieldEpisodeNumber, field.TypeInt, value)
		_node.EpisodeNumber = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(schedule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(schedule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AnimeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedule.AnimeTable,
			Columns: []string{schedule.AnimeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(anime.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AnimeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Schedule.Create().
//		SetAnimeID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ScheduleUpsert) {
//			SetAnimeID(v+v).
//		}).
//		Exec(ctx)
func (_c *ScheduleCreate) OnConflict(opts ...sql.ConflictOption) *ScheduleUpsertOne {
	_c.conflict = opts
	return &ScheduleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Schedule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ScheduleCreate) OnConflictColumns(columns ...string) *ScheduleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ScheduleUpsertOne{
		create: _c,
	}
}

type (
	// ScheduleUpsertOne is the builder for "upsert"-ing
	//  one Schedule node.
	ScheduleUpsertOne struct {
		create *ScheduleCreate
	}

	// ScheduleUpsert is the "OnConflict" setter.
	ScheduleUpsert struct {
		*sql.UpdateSet
	}
)

// SetAnimeID sets the "anime_id" field.
func (u *ScheduleUpsert) SetAnimeID(v int64) *ScheduleUpsert {
	u.Set(schedule.FieldAnimeID, v)
	return u
}

// UpdateAnimeID sets the "anime_id" field to the value that was provided on create.
func (u *ScheduleUpsert) UpdateAnimeID() *ScheduleUpsert {
	u.SetExcluded(schedule.FieldAnimeID)
	return u
}

// SetReleaseDatetime sets the "release_datetime" field.
func (u *ScheduleUpsert) SetReleaseDatetime(v time.Time) *ScheduleUpsert {
	u.Set(schedule.FieldReleaseDatetime, v)
	return u
}

// UpdateReleaseDatetime sets the "release_datetime" field to the value that was provided on create.
func (u *ScheduleUpsert) UpdateReleaseDatetime() *ScheduleUpsert {
	u.SetExcluded(schedule.FieldReleaseDatetime)
	return u
}

// SetEpisodeNumber sets the "episode_number" field.
func (u *ScheduleUpsert) SetEpisodeNumber(v int) *ScheduleUpsert {
	u.Set(schedule.FieldEpisodeNumber, v)
	return u
}

// UpdateEpisodeNumber sets the "episode_number" field to the value that was provided on create.
func (u *ScheduleUpsert) UpdateEpisodeNumber() *ScheduleUpsert {
	u.SetExcluded(schedule.FieldEpisodeNumber)
	return u
}

// AddEpisodeNumber adds v to the "episode_number" field.
func (u *ScheduleUpsert) AddEpisodeNumber(v int) *ScheduleUpsert {
	u.Add(schedule.FieldEpisodeNumber, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ScheduleUpsert) SetCreatedAt(v time.Time) *ScheduleUpsert {
	u.Set(schedule.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ScheduleUpsert) UpdateCreatedAt() *ScheduleUpsert {
	u.SetExcluded(schedule.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ScheduleUpsert) SetUpdatedAt(v time.Time) *ScheduleUpsert {
	u.Set(schedule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ScheduleUpsert) UpdateUpdatedAt() *ScheduleUpsert {
	u.SetExcluded(schedule.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Schedule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(schedule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ScheduleUpsertOne) UpdateNewValues() *ScheduleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(schedule.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Schedule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ScheduleUpsertOne) Ignore() *ScheduleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ScheduleUpsertOne) DoNothing() *ScheduleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ScheduleCreate.OnConflict
// documentation for more info.
func (u *ScheduleUpsertOne) Update(set func(*ScheduleUpsert)) *ScheduleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ScheduleUpsert{UpdateSet: update})
	}))
	return u
}

// SetAnimeID sets the "anime_id" field.
func (u *ScheduleUpsertOne) SetAnimeID(v int64) *ScheduleUpsertOne {
	return u.Update(func(s *ScheduleUpsert) {
		s.SetAnimeID(v)
	})
}

// UpdateAnimeID sets the "anime_id" field to the value that was provided on create.
func (u *ScheduleUpsertOne) UpdateAnimeID() *ScheduleUpsertOne {
	return u.Update(func(s *ScheduleUpsert) {
		s.UpdateAnimeID()
	})
}

// SetReleaseDatetime sets the "release_datetime" field.
func (u *ScheduleUpsertOne) SetReleaseDatetime(v time.Time) *ScheduleUpsertOne {
	return u.Update(func(s *ScheduleUpsert) {
		s.SetReleaseDatetime(v)
	})
}

// UpdateReleaseDatetime sets the "release_datetime" field to the value that was provided on create.
func (u *ScheduleUpsertOne) UpdateReleaseDatetime() *ScheduleUpsertOne {
	return u.Update(func(s *ScheduleUpsert) {
		s.UpdateReleaseDatetime()
	})
}

// SetEpisodeNumber sets the "episode_number" field.
func (u *ScheduleUpsertOne) SetEpisodeNumber(v int) *ScheduleUpsertOne {
	return u.Update(func(s *ScheduleUpsert) {
		s.SetEpisodeNumber(v)
	})
}

// AddEpisodeNumber adds v to the "episode_number" field.
func (u *ScheduleUpsertOne) AddEpisodeNumber(v int) *ScheduleUpsertOne {
	return u.Update(func(s *ScheduleUpsert) {
		s.AddEpisodeNumber(v)
	})
}

// UpdateEpisodeNumber sets the "episode_number" field to the value that was provided on create.
func (u *ScheduleUpsertOne) UpdateEpisodeNumber() *ScheduleUpsertOne {
	return u.Update(func(s *ScheduleUpsert) {
		s.UpdateEpisodeNumber()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ScheduleUpsertOne) SetCreatedAt(v time.Time) *ScheduleUpsertOne {
	return u.Update(func(s *ScheduleUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ScheduleUpsertOne) UpdateCreatedAt() *ScheduleUpsertOne {
	return u.Update(func(s *ScheduleUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ScheduleUpsertOne) SetUpdatedAt(v time.Time) *ScheduleUpsertOne {
	return u.Update(func(s *ScheduleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ScheduleUpsertOne) UpdateUpdatedAt() *ScheduleUpsertOne {
	return u.Update(func(s *ScheduleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ScheduleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ScheduleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ScheduleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ScheduleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ScheduleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ScheduleCreateBulk is the builder for creating many Schedule entities in bulk.
type ScheduleCreateBulk struct {
	config
	err      error
	builders []*ScheduleCreate
	conflict []sql.ConflictOption
}

// Save creates the Schedule entities in the database.
func (_c *ScheduleCreateBulk) Save(ctx context.Context) ([]*Schedule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Schedule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScheduleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScheduleCreateBulk) SaveX(ctx context.Context) []*Schedule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Schedule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ScheduleUpsert) {
//			SetAnimeID(v+v).
//		}).
//		Exec(ctx)
func (_c *ScheduleCreateBulk) OnConflict(opts ...sql.ConflictOption) *ScheduleUpsertBulk {
	_c.conflict = opts
	return &ScheduleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Schedule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ScheduleCreateBulk) OnConflictColumns(columns ...string) *ScheduleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ScheduleUpsertBulk{
		create: _c,
	}
}

// ScheduleUpsertBulk is the builder for "upsert"-ing
// a bulk of Schedule nodes.
type ScheduleUpsertBulk struct {
	create *ScheduleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Schedule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(schedule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ScheduleUpsertBulk) UpdateNewValues() *ScheduleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(schedule.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Schedule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ScheduleUpsertBulk) Ignore() *ScheduleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ScheduleUpsertBulk) DoNothing() *ScheduleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ScheduleCreateBulk.OnConflict
// documentation for more info.
func (u *ScheduleUpsertBulk) Update(set func(*ScheduleUpsert)) *ScheduleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ScheduleUpsert{UpdateSet: update})
	}))
	return u
}

// SetAnimeID sets the "anime_id" field.
func (u *ScheduleUpsertBulk) SetAnimeID(v int64) *ScheduleUpsertBulk {
	return u.Update(func(s *ScheduleUpsert) {
		s.SetAnimeID(v)
	})
}

// UpdateAnimeID sets the "anime_id" field to the value that was provided on create.
func (u *ScheduleUpsertBulk) UpdateAnimeID() *ScheduleUpsertBulk {
	return u.Update(func(s *ScheduleUpsert) {
		s.UpdateAnimeID()
	})
}

// SetReleaseDatetime sets the "release_datetime" field.
func (u *ScheduleUpsertBulk) SetReleaseDatetime(v time.Time) *ScheduleUpsertBulk {
	return u.Update(func(s *ScheduleUpsert) {
		s.SetReleaseDatetime(v)
	})
}

// UpdateReleaseDatetime sets the "release_datetime" field to the value that was provided on create.
func (u *ScheduleUpsertBulk) UpdateReleaseDatetime() *ScheduleUpsertBulk {
	return u.Update(func(s *ScheduleUpsert) {
		s.UpdateReleaseDatetime()
	})
}

// SetEpisodeNumber sets the "episode_number" field.
func (u *ScheduleUpsertBulk) SetEpisodeNumber(v int) *ScheduleUpsertBulk {
	return u.Update(func(s *ScheduleUpsert) {
		s.SetEpisodeNumber(v)
	})
}

// AddEpisodeNumber adds v to the "episode_number" field.
func (u *ScheduleUpsertBulk) AddEpisodeNumber(v int) *ScheduleUpsertBulk {
	return u.Update(func(s *ScheduleUpsert) {
		s.AddEpisodeNumber(v)
	})
}

// UpdateEpisodeNumber sets the "episode_number" field to the value that was provided on create.
func (u *ScheduleUpsertBulk) UpdateEpisodeNumber() *ScheduleUpsertBulk {
	return u.Update(func(s *ScheduleUpsert) {
		s.UpdateEpisodeNumber()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ScheduleUpsertBulk) SetCreatedAt(v time.Time) *ScheduleUpsertBulk {
	return u.Update(func(s *ScheduleUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ScheduleUpsertBulk) UpdateCreatedAt() *ScheduleUpsertBulk {
	return u.Update(func(s *ScheduleUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ScheduleUpsertBulk) SetUpdatedAt(v time.Time) *ScheduleUpsertBulk {
	return u.Update(func(s *ScheduleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ScheduleUpsertBulk) UpdateUpdatedAt() *ScheduleUpsertBulk {
	return u.Update(func(s *ScheduleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ScheduleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ScheduleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ScheduleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ScheduleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
