// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/seva/animevista/ent/anime"
	"github.com/seva/animevista/ent/predicate"
	"github.com/seva/animevista/ent/schedule"
)

// ScheduleUpdate is the builder for updating Schedule entities.
type ScheduleUpdate struct {
	config
	hooks    []Hook
	mutation *ScheduleMutation
}

// Where appends a list predicates to the ScheduleUpdate builder.
func (_u *ScheduleUpdate) Where(ps ...predicate.Schedule) *ScheduleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAnimeID sets the "anime_id" field.
func (_u *ScheduleUpdate) SetAnimeID(v int64) *ScheduleUpdate {
	_u.mutation.SetAnimeID(v)
	return _u
}

// SetNillableAnimeID sets the "anime_id" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableAnimeID(v *int64) *ScheduleUpdate {
	if v != nil {
		_u.SetAnimeID(*v)
	}
	return _u
}

// SetReleaseDatetime sets the "release_datetime" field.
func (_u *ScheduleUpdate) SetReleaseDatetime(v time.Time) *ScheduleUpdate {
	_u.mutation.SetReleaseDatetime(v)
	return _u
}

// SetNillableReleaseDatetime sets the "release_datetime" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableReleaseDatetime(v *time.Time) *ScheduleUpdate {
	if v != nil {
		_u.SetReleaseDatetime(*v)
	}
	return _u
}

// SetEpisodeNumber sets the "episode_number" field.
func (_u *ScheduleUpdate) SetEpisodeNumber(v int) *ScheduleUpdate {
	_u.mutation.ResetEpisodeNumber()
	_u.mutation.SetEpisodeNumber(v)
	return _u
}

// SetNillableEpisodeNumber sets the "episode_number" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableEpisodeNumber(v *int) *ScheduleUpdate {
	if v != nil {
		_u.SetEpisodeNumber(*v)
	}
	return _u
}

// AddEpisodeNumber adds value to the "episode_number" field.
func (_u *ScheduleUpdate) AddEpisodeNumber(v int) *ScheduleUpdate {
	_u.mutation.AddEpisodeNumber(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ScheduleUpdate) SetCreatedAt(v time.Time) *ScheduleUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableCreatedAt(v *time.Time) *ScheduleUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScheduleUpdate) SetUpdatedAt(v time.Time) *ScheduleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAnime sets the "anime" edge to the Anime entity.
func (_u *ScheduleUpdate) SetAnime(v *Anime) *ScheduleUpdate {
	return _u.SetAnimeID(v.ID)
}

// Mutation returns the ScheduleMutation object of the builder.
func (_u *ScheduleUpdate) Mutation() *ScheduleMutation {
	return _u.mutation
}

// ClearAnime clears the "anime" edge to the Anime entity.
func (_u *ScheduleUpdate) ClearAnime() *ScheduleUpdate {
	_u.mutation.ClearAnime()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScheduleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScheduleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScheduleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := schedule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScheduleUpdate) check() error {
	if _u.mutation.AnimeCleared() && len(_u.mutation.AnimeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Schedule.anime"`)
	}
	return nil
}

func (_u *ScheduleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schedule.Table, schedule.Columns, sqlgraph.NewFieldSpec(schedule.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReleaseDatetime(); ok {
		_spec.SetField(schedule.FieldReleaseDatetime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EpisodeNumber(); ok {
		_spec.SetField(schedule.FieldEpisodeNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEpisodeNumber(); ok {
		_spec.AddField(schedule.FieldEpisodeNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(schedule.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(schedule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AnimeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedule.AnimeTable,
			Columns: []string{schedule.AnimeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(anime.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnimeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedule.AnimeTable,
			Columns: []string{schedule.AnimeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(anime.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScheduleUpdateOne is the builder for updating a single Schedule entity.
type ScheduleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScheduleMutation
}

// SetAnimeID sets the "anime_id" field.
func (_u *ScheduleUpdateOne) SetAnimeID(v int64) *ScheduleUpdateOne {
	_u.mutation.SetAnimeID(v)
	return _u
}

// SetNillableAnimeID sets the "anime_id" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableAnimeID(v *int64) *ScheduleUpdateOne {
	if v != nil {
		_u.SetAnimeID(*v)
	}
	return _u
}

// SetReleaseDatetime sets the "release_datetime" field.
func (_u *ScheduleUpdateOne) SetReleaseDatetime(v time.Time) *ScheduleUpdateOne {
	_u.mutation.SetReleaseDatetime(v)
	return _u
}

// SetNillableReleaseDatetime sets the "release_datetime" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableReleaseDatetime(v *time.Time) *ScheduleUpdateOne {
	if v != nil {
		_u.SetReleaseDatetime(*v)
	}
	return _u
}

// SetEpisodeNumber sets the "episode_number" field.
func (_u *ScheduleUpdateOne) SetEpisodeNumber(v int) *ScheduleUpdateOne {
	_u.mutation.ResetEpisodeNumber()
	_u.mutation.SetEpisodeNumber(v)
	return _u
}

// SetNillableEpisodeNumber sets the "episode_number" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableEpisodeNumber(v *int) *ScheduleUpdateOne {
	if v != nil {
		_u.SetEpisodeNumber(*v)
	}
	return _u
}

// AddEpisodeNumber adds value to the "episode_number" field.
func (_u *ScheduleUpdateOne) AddEpisodeNumber(v int) *ScheduleUpdateOne {
	_u.mutation.AddEpisodeNumber(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ScheduleUpdateOne) SetCreatedAt(v time.Time) *ScheduleUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableCreatedAt(v *time.Time) *ScheduleUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScheduleUpdateOne) SetUpdatedAt(v time.Time) *ScheduleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAnime sets the "anime" edge to the Anime entity.
func (_u *ScheduleUpdateOne) SetAnime(v *Anime) *ScheduleUpdateOne {
	return _u.SetAnimeID(v.ID)
}

// Mutation returns the ScheduleMutation object of the builder.
func (_u *ScheduleUpdateOne) Mutation() *ScheduleMutation {
	return _u.mutation
}

// ClearAnime clears the "anime" edge to the Anime entity.
func (_u *ScheduleUpdateOne) ClearAnime() *ScheduleUpdateOne {
	_u.mutation.ClearAnime()
	return _u
}

// Where appends a list predicates to the ScheduleUpdate builder.
func (_u *ScheduleUpdateOne) Where(ps ...predicate.Schedule) *ScheduleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScheduleUpdateOne) Select(field string, fields ...string) *ScheduleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Schedule entity.
func (_u *ScheduleUpdateOne) Save(ctx context.Context) (*Schedule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduleUpdateOne) SaveX(ctx context.Context) *Schedule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScheduleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScheduleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := schedule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScheduleUpdateOne) check() error {
	if _u.mutation.AnimeCleared() && len(_u.mutation.AnimeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Schedule.anime"`)
	}
	return nil
}

func (_u *ScheduleUpdateOne) sqlSave(ctx context.Context) (_node *Schedule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schedule.Table, schedule.Columns, sqlgraph.NewFieldSpec(schedule.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Schedule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schedule.FieldID)
		for _, f := range fields {
			if !schedule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != schedule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReleaseDatetime(); ok {
		_spec.SetField(schedule.FieldReleaseDatetime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EpisodeNumber(); ok {
		_spec.SetField(schedule.FieldEpisodeNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEpisodeNumber(); ok {
		_spec.AddField(schedule.FieldEpisodeNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(schedule.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(schedule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AnimeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedule.AnimeTable,
			Columns: []string{schedule.AnimeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(anime.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnimeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedule.AnimeTable,
			Columns: []string{schedule.AnimeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(anime.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Schedule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
