// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/seva/animevista/ent/userrating"
)

// UserRatingCreate is the builder for creating a UserRating entity.
type UserRatingCreate struct {
	config
	mutation *UserRatingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserRatingCreate) SetUserID(v int64) *UserRatingCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAnimeID sets the "anime_id" field.
func (_c *UserRatingCreate) SetAnimeID(v int64) *UserRatingCreate {
	_c.mutation.SetAnimeID(v)
	return _c
}

// SetRating sets the "rating" field.
func (_c *UserRatingCreate) SetRating(v float64) *UserRatingCreate {
	_c.mutation.SetRating(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserRatingCreate) SetCreatedAt(v time.Time) *UserRatingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserRatingCreate) SetNillableCreatedAt(v *time.Time) *UserRatingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserRatingCreate) SetUpdatedAt(v time.Time) *UserRatingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserRatingCreate) SetNillableUpdatedAt(v *time.Time) *UserRatingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserRatingCreate) SetID(v int64) *UserRatingCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UserRatingMutation object of the builder.
func (_c *UserRatingCreate) Mutation() *UserRatingMutation {
	return _c.mutation
}

// Save creates the UserRating in the database.
func (_c *UserRatingCreate) Save(ctx context.Context) (*UserRating, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserRatingCreate) SaveX(ctx context.Context) *UserRating {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserRatingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserRatingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserRatingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userrating.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userrating.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserRatingCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserRating.user_id"`)}
	}
	if _, ok := _c.mutation.AnimeID(); !ok {
		return &ValidationError{Name: "anime_id", err: errors.New(`ent: missing required field "UserRating.anime_id"`)}
	}
	if _, ok := _c.mutation.Rating(); !ok {
		return &ValidationError{Name: "rating", err: errors.New(`ent: missing required field "UserRating.rating"`)}
	}
	if v, ok := _c.mutation.Rating(); ok {
		if err := userrating.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "UserRating.rating": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserRating.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserRating.updated_at"`)}
	}
	return nil
}

func (_c *UserRatingCreate) sqlSave(ctx context.Context) (*UserRating, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserRatingCreate) createSpec() (*UserRating, *sqlgraph.CreateSpec) {
	var (
		_node = &UserRating{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userrating.Table, sqlgraph.NewFieldSpec(userrating.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userrating.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.AnimeID(); ok {
		_spec.SetField(userrating.FieldAnimeID, field.TypeInt64, value)
		_node.AnimeID = value
	}
	if value, ok := _c.mutation.Rating(); ok {
		_spec.SetField(userrating.FieldRating, field.TypeFloat64, value)
		_node.Rating = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userrating.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userrating.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserRating.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserRatingUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserRatingCreate) OnConflict(opts ...sql.ConflictOption) *UserRatingUpsertOne {
	_c.conflict = opts
	return &UserRatingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserRating.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserRatingCreate) OnConflictColumns(columns ...string) *UserRatingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserRatingUpsertOne{
		create: _c,
	}
}

type (
	// UserRatingUpsertOne is the builder for "upsert"-ing
	//  one UserRating node.
	UserRatingUpsertOne struct {
		create *UserRatingCreate
	}

	// UserRatingUpsert is the "OnConflict" setter.
	UserRatingUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserRatingUpsert) SetUserID(v int64) *UserRatingUpsert {
	u.Set(userrating.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRatingUpsert) UpdateUserID() *UserRatingUpsert {
	u.SetExcluded(userrating.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UserRatingUpsert) AddUserID(v int64) *UserRatingUpsert {
	u.Add(userrating.FieldUserID, v)
	return u
}

// SetAnimeID sets the "anime_id" field.
func (u *UserRatingUpsert) SetAnimeID(v int64) *UserRatingUpsert {
	u.Set(userrating.FieldAnimeID, v)
	return u
}

// UpdateAnimeID sets the "anime_id" field to the value that was provided on create.
func (u *UserRatingUpsert) UpdateAnimeID() *UserRatingUpsert {
	u.SetExcluded(userrating.FieldAnimeID)
	return u
}

// AddAnimeID adds v to the "anime_id" field.
func (u *UserRatingUpsert) AddAnimeID(v int64) *UserRatingUpsert {
	u.Add(userrating.FieldAnimeID, v)
	return u
}

// SetRating sets the "rating" field.
func (u *UserRatingUpsert) SetRating(v float64) *UserRatingUpsert {
	u.Set(userrating.FieldRating, v)
	return u
}

// UpdateRating sets the "rating" field to the value that was provided on create.
func (u *UserRatingUpsert) UpdateRating() *UserRatingUpsert {
	u.SetExcluded(userrating.FieldRating)
	return u
}

// AddRating adds v to the "rating" field.
func (u *UserRatingUpsert) AddRating(v float64) *UserRatingUpsert {
	u.Add(userrating.FieldRating, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *UserRatingUpsert) SetCreatedAt(v time.Time) *UserRatingUpsert {
	u.Set(userrating.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserRatingUpsert) UpdateCreatedAt() *UserRatingUpsert {
	u.SetExcluded(userrating.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRatingUpsert) SetUpdatedAt(v time.Time) *UserRatingUpsert {
	u.Set(userrating.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRatingUpsert) UpdateUpdatedAt() *UserRatingUpsert {
	u.SetExcluded(userrating.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UserRating.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(userrating.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserRatingUpsertOne) UpdateNewValues() *UserRatingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(userrating.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserRating.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserRatingUpsertOne) Ignore() *UserRatingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserRatingUpsertOne) DoNothing() *UserRatingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserRatingCreate.OnConflict
// documentation for more info.
func (u *UserRatingUpsertOne) Update(set func(*UserRatingUpsert)) *UserRatingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserRatingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserRatingUpsertOne) SetUserID(v int64) *UserRatingUpsertOne {
	return u.Update(func(s *UserRatingUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserRatingUpsertOne) AddUserID(v int64) *UserRatingUpsertOne {
	return u.Update(func(s *UserRatingUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRatingUpsertOne) UpdateUserID() *UserRatingUpsertOne {
	return u.Update(func(s *UserRatingUpsert) {
		s.UpdateUserID()
	})
}

// SetAnimeID sets the "anime_id" field.
func (u *UserRatingUpsertOne) SetAnimeID(v int64) *UserRatingUpsertOne {
	return u.Update(func(s *UserRatingUpsert) {
		s.SetAnimeID(v)
	})
}

// AddAnimeID adds v to the "anime_id" field.
func (u *UserRatingUpsertOne) AddAnimeID(v int64) *UserRatingUpsertOne {
	return u.Update(func(s *UserRatingUpsert) {
		s.AddAnimeID(v)
	})
}

// UpdateAnimeID sets the "anime_id" field to the value that was provided on create.
func (u *UserRatingUpsertOne) UpdateAnimeID() *UserRatingUpsertOne {
	return u.Update(func(s *UserRatingUpsert) {
		s.UpdateAnimeID()
	})
}

// SetRating sets the "rating" field.
func (u *UserRatingUpsertOne) SetRating(v float64) *UserRatingUpsertOne {
	return u.Update(func(s *UserRatingUpsert) {
		s.SetRating(v)
	})
}

// AddRating adds v to the "rating" field.
func (u *UserRatingUpsertOne) AddRating(v float64) *UserRatingUpsertOne {
	return u.Update(func(s *UserRatingUpsert) {
		s.AddRating(v)
	})
}

// UpdateRating sets the "rating" field to the value that was provided on create.
func (u *UserRatingUpsertOne) UpdateRating() *UserRatingUpsertOne {
	return u.Update(func(s *UserRatingUpsert) {
		s.UpdateRating()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UserRatingUpsertOne) SetCreatedAt(v time.Time) *UserRatingUpsertOne {
	return u.Update(func(s *UserRatingUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserRatingUpsertOne) UpdateCreatedAt() *UserRatingUpsertOne {
	return u.Update(func(s *UserRatingUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRatingUpsertOne) SetUpdatedAt(v time.Time) *UserRatingUpsertOne {
	return u.Update(func(s *UserRatingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRatingUpsertOne) UpdateUpdatedAt() *UserRatingUpsertOne {
	return u.Update(func(s *UserRatingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserRatingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserRatingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserRatingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserRatingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserRatingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserRatingCreateBulk is the builder for creating many UserRating entities in bulk.
type UserRatingCreateBulk struct {
	config
	err      error
	builders []*UserRatingCreate
	conflict []sql.ConflictOption
}

// Save creates the UserRating entities in the database.
func (_c *UserRatingCreateBulk) Save(ctx context.Context) ([]*UserRating, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserRating, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserRatingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserRatingCreateBulk) SaveX(ctx context.Context) []*UserRating {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserRatingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserRatingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserRating.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserRatingUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserRatingCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserRatingUpsertBulk {
	_c.conflict = opts
	return &UserRatingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserRating.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserRatingCreateBulk) OnConflictColumns(columns ...string) *UserRatingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserRatingUpsertBulk{
		create: _c,
	}
}

// UserRatingUpsertBulk is the builder for "upsert"-ing
// a bulk of UserRating nodes.
type UserRatingUpsertBulk struct {
	create *UserRatingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserRating.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(userrating.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserRatingUpsertBulk) UpdateNewValues() *UserRatingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(userrating.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserRating.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserRatingUpsertBulk) Ignore() *UserRatingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserRatingUpsertBulk) DoNothing() *UserRatingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserRatingCreateBulk.OnConflict
// documentation for more info.
func (u *UserRatingUpsertBulk) Update(set func(*UserRatingUpsert)) *UserRatingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserRatingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserRatingUpsertBulk) SetUserID(v int64) *UserRatingUpsertBulk {
	return u.Update(func(s *UserRatingUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserRatingUpsertBulk) AddUserID(v int64) *UserRatingUpsertBulk {
	return u.Update(func(s *UserRatingUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRatingUpsertBulk) UpdateUserID() *UserRatingUpsertBulk {
	return u.Update(func(s *UserRatingUpsert) {
		s.UpdateUserID()
	})
}

// SetAnimeID sets the "anime_id" field.
func (u *UserRatingUpsertBulk) SetAnimeID(v int64) *UserRatingUpsertBulk {
	return u.Update(func(s *UserRatingUpsert) {
		s.SetAnimeID(v)
	})
}

// AddAnimeID adds v to the "anime_id" field.
func (u *UserRatingUpsertBulk) AddAnimeID(v int64) *UserRatingUpsertBulk {
	return u.Update(func(s *UserRatingUpsert) {
		s.AddAnimeID(v)
	})
}

// UpdateAnimeID sets the "anime_id" field to the value that was provided on create.
func (u *UserRatingUpsertBulk) UpdateAnimeID() *UserRatingUpsertBulk {
	return u.Update(func(s *UserRatingUpsert) {
		s.UpdateAnimeID()
	})
}

// SetRating sets the "rating" field.
func (u *UserRatingUpsertBulk) SetRating(v float64) *UserRatingUpsertBulk {
	return u.Update(func(s *UserRatingUpsert) {
		s.SetRating(v)
	})
}

// AddRating adds v to the "rating" field.
func (u *UserRatingUpsertBulk) AddRating(v float64) *UserRatingUpsertBulk {
	return u.Update(func(s *UserRatingUpsert) {
		s.AddRating(v)
	})
}

// UpdateRating sets the "rating" field to the value that was provided on create.
func (u *UserRatingUpsertBulk) UpdateRating() *UserRatingUpsertBulk {
	return u.Update(func(s *UserRatingUpsert) {
		s.UpdateRating()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UserRatingUpsertBulk) SetCreatedAt(v time.Time) *UserRatingUpsertBulk {
	return u.Update(func(s *UserRatingUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserRatingUpsertBulk) UpdateCreatedAt() *UserRatingUpsertBulk {
	return u.Update(func(s *UserRatingUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRatingUpsertBulk) SetUpdatedAt(v time.Time) *UserRatingUpsertBulk {
	return u.Update(func(s *UserRatingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRatingUpsertBulk) UpdateUpdatedAt() *UserRatingUpsertBulk {
	return u.Update(func(s *UserRatingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserRatingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserRatingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserRatingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserRatingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
