// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/seva/animevista/ent/predicate"
	"github.com/seva/animevista/ent/userrating"
)

// UserRatingUpdate is the builder for updating UserRating entities.
type UserRatingUpdate struct {
	config
	hooks    []Hook
	mutation *UserRatingMutation
}

// Where appends a list predicates to the UserRatingUpdate builder.
func (_u *UserRatingUpdate) Where(ps ...predicate.UserRating) *UserRatingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserRatingUpdate) SetUserID(v int64) *UserRatingUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserRatingUpdate) SetNillableUserID(v *int64) *UserRatingUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserRatingUpdate) AddUserID(v int64) *UserRatingUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAnimeID sets the "anime_id" field.
func (_u *UserRatingUpdate) SetAnimeID(v int64) *UserRatingUpdate {
	_u.mutation.ResetAnimeID()
	_u.mutation.SetAnimeID(v)
	return _u
}

// SetNillableAnimeID sets the "anime_id" field if the given value is not nil.
func (_u *UserRatingUpdate) SetNillableAnimeID(v *int64) *UserRatingUpdate {
	if v != nil {
		_u.SetAnimeID(*v)
	}
	return _u
}

// AddAnimeID adds value to the "anime_id" field.
func (_u *UserRatingUpdate) AddAnimeID(v int64) *UserRatingUpdate {
	_u.mutation.AddAnimeID(v)
	return _u
}

// SetRating sets the "rating" field.
func (_u *UserRatingUpdate) SetRating(v float64) *UserRatingUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *UserRatingUpdate) SetNillableRating(v *float64) *UserRatingUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *UserRatingUpdate) AddRating(v float64) *UserRatingUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserRatingUpdate) SetCreatedAt(v time.Time) *UserRatingUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserRatingUpdate) SetNillableCreatedAt(v *time.Time) *UserRatingUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserRatingUpdate) SetUpdatedAt(v time.Time) *UserRatingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserRatingMutation object of the builder.
func (_u *UserRatingUpdate) Mutation() *UserRatingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserRatingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserRatingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserRatingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserRatingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserRatingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userrating.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserRatingUpdate) check() error {
	if v, ok := _u.mutation.Rating(); ok {
		if err := userrating.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "UserRating.rating": %w`, err)}
		}
	}
	return nil
}

func (_u *UserRatingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userrating.Table, userrating.Columns, sqlgraph.NewFieldSpec(userrating.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userrating.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(userrating.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AnimeID(); ok {
		_spec.SetField(userrating.FieldAnimeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAnimeID(); ok {
		_spec.AddField(userrating.FieldAnimeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(userrating.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(userrating.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(userrating.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userrating.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userrating.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserRatingUpdateOne is the builder for updating a single UserRating entity.
type UserRatingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserRatingMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserRatingUpdateOne) SetUserID(v int64) *UserRatingUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserRatingUpdateOne) SetNillableUserID(v *int64) *UserRatingUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserRatingUpdateOne) AddUserID(v int64) *UserRatingUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAnimeID sets the "anime_id" field.
func (_u *UserRatingUpdateOne) SetAnimeID(v int64) *UserRatingUpdateOne {
	_u.mutation.ResetAnimeID()
	_u.mutation.SetAnimeID(v)
	return _u
}

// SetNillableAnimeID sets the "anime_id" field if the given value is not nil.
func (_u *UserRatingUpdateOne) SetNillableAnimeID(v *int64) *UserRatingUpdateOne {
	if v != nil {
		_u.SetAnimeID(*v)
	}
	return _u
}

// AddAnimeID adds value to the "anime_id" field.
func (_u *UserRatingUpdateOne) AddAnimeID(v int64) *UserRatingUpdateOne {
	_u.mutation.AddAnimeID(v)
	return _u
}

// SetRating sets the "rating" field.
func (_u *UserRatingUpdateOne) SetRating(v float64) *UserRatingUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *UserRatingUpdateOne) SetNillableRating(v *float64) *UserRatingUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *UserRatingUpdateOne) AddRating(v float64) *UserRatingUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserRatingUpdateOne) SetCreatedAt(v time.Time) *UserRatingUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserRatingUpdateOne) SetNillableCreatedAt(v *time.Time) *UserRatingUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserRatingUpdateOne) SetUpdatedAt(v time.Time) *UserRatingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserRatingMutation object of the builder.
func (_u *UserRatingUpdateOne) Mutation() *UserRatingMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserRatingUpdate builder.
func (_u *UserRatingUpdateOne) Where(ps ...predicate.UserRating) *UserRatingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserRatingUpdateOne) Select(field string, fields ...string) *UserRatingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserRating entity.
func (_u *UserRatingUpdateOne) Save(ctx context.Context) (*UserRating, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserRatingUpdateOne) SaveX(ctx context.Context) *UserRating {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserRatingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserRatingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserRatingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userrating.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserRatingUpdateOne) check() error {
	if v, ok := _u.mutation.Rating(); ok {
		if err := userrating.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "UserRating.rating": %w`, err)}
		}
	}
	return nil
}

func (_u *UserRatingUpdateOne) sqlSave(ctx context.Context) (_node *UserRating, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userrating.Table, userrating.Columns, sqlgraph.NewFieldSpec(userrating.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserRating.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userrating.FieldID)
		for _, f := range fields {
			if !userrating.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userrating.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userrating.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(userrating.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AnimeID(); ok {
		_spec.SetField(userrating.FieldAnimeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAnimeID(); ok {
		_spec.AddField(userrating.FieldAnimeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(userrating.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(userrating.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(userrating.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userrating.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UserRating{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userrating.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
