// Code generated by ent, DO NOT EDIT.

package schedule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the schedule type in the database.
	Label = "schedule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAnimeID holds the string denoting the anime_id field in the database.
	FieldAnimeID = "anime_id"
	// FieldReleaseDatetime holds the string denoting the release_datetime field in the database.
	FieldReleaseDatetime = "release_datetime"
	// FieldEpisodeNumber holds the string denoting the episode_number field in the database.
	FieldEpisodeNumber = "episode_number"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeAnime holds the string denoting the anime edge name in mutations.
	EdgeAnime = "anime"
	// Table holds the table name of the schedule in the database.
	Table = "schedules"
	// AnimeTable is the table that holds the anime relation/edge.
	AnimeTable = "schedules"
	// AnimeInverseTable is the table name for the Anime entity.
	// It exists in this package in order to avoid circular dependency with the "anime" package.
	AnimeInverseTable = "anime"
	// AnimeColumn is the table column denoting the anime relation/edge.
	AnimeColumn = "anime_id"
)

// Columns holds all SQL columns for schedule fields.
var Columns = []string{
	FieldID,
	FieldAnimeID,
	FieldReleaseDatetime,
	FieldEpisodeNumber,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Schedule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAnimeID orders the results by the anime_id field.
func ByAnimeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnimeID, opts...).ToFunc()
}

// ByReleaseDatetime orders the results by the release_datetime field.
func ByReleaseDatetime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleaseDatetime, opts...).ToFunc()
}

// ByEpisodeNumber orders the results by the episode_number field.
func ByEpisodeNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEpisodeNumber, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAnimeField orders the results by anime field.
func ByAnimeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAnimeStep(), sql.OrderByField(field, opts...))
	}
}
func newAnimeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AnimeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AnimeTable, AnimeColumn),
	)
}
