// Code generated by ent, DO NOT EDIT.

package schedule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/seva/animevista/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldID, id))
}

// AnimeID applies equality check predicate on the "anime_id" field. It's identical to AnimeIDEQ.
func AnimeID(v int64) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldAnimeID, v))
}

// ReleaseDatetime applies equality check predicate on the "release_datetime" field. It's identical to ReleaseDatetimeEQ.
func ReleaseDatetime(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldReleaseDatetime, v))
}

// EpisodeNumber applies equality check predicate on the "episode_number" field. It's identical to EpisodeNumberEQ.
func EpisodeNumber(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldEpisodeNumber, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldUpdatedAt, v))
}

// AnimeIDEQ applies the EQ predicate on the "anime_id" field.
func AnimeIDEQ(v int64) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldAnimeID, v))
}

// AnimeIDNEQ applies the NEQ predicate on the "anime_id" field.
func AnimeIDNEQ(v int64) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldAnimeID, v))
}

// AnimeIDIn applies the In predicate on the "anime_id" field.
func AnimeIDIn(vs ...int64) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldAnimeID, vs...))
}

// AnimeIDNotIn applies the NotIn predicate on the "anime_id" field.
func AnimeIDNotIn(vs ...int64) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldAnimeID, vs...))
}

// ReleaseDatetimeEQ applies the EQ predicate on the "release_datetime" field.
func ReleaseDatetimeEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldReleaseDatetime, v))
}

// ReleaseDatetimeNEQ applies the NEQ predicate on the "release_datetime" field.
func ReleaseDatetimeNEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldReleaseDatetime, v))
}

// ReleaseDatetimeIn applies the In predicate on the "release_datetime" field.
func ReleaseDatetimeIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldReleaseDatetime, vs...))
}

// ReleaseDatetimeNotIn applies the NotIn predicate on the "release_datetime" field.
func ReleaseDatetimeNotIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldReleaseDatetime, vs...))
}

// ReleaseDatetimeGT applies the GT predicate on the "release_datetime" field.
func ReleaseDatetimeGT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldReleaseDatetime, v))
}

// ReleaseDatetimeGTE applies the GTE predicate on the "release_datetime" field.
func ReleaseDatetimeGTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldReleaseDatetime, v))
}

// ReleaseDatetimeLT applies the LT predicate on the "release_datetime" field.
func ReleaseDatetimeLT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldReleaseDatetime, v))
}

// ReleaseDatetimeLTE applies the LTE predicate on the "release_datetime" field.
func ReleaseDatetimeLTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldReleaseDatetime, v))
}

// EpisodeNumberEQ applies the EQ predicate on the "episode_number" field.
func EpisodeNumberEQ(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldEpisodeNumber, v))
}

// EpisodeNumberNEQ applies the NEQ predicate on the "episode_number" field.
func EpisodeNumberNEQ(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldEpisodeNumber, v))
}

// EpisodeNumberIn applies the In predicate on the "episode_number" field.
func EpisodeNumberIn(vs ...int) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldEpisodeNumber, vs...))
}

// EpisodeNumberNotIn applies the NotIn predicate on the "episode_number" field.
func EpisodeNumberNotIn(vs ...int) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldEpisodeNumber, vs...))
}

// EpisodeNumberGT applies the GT predicate on the "episode_number" field.
func EpisodeNumberGT(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldEpisodeNumber, v))
}

// EpisodeNumberGTE applies the GTE predicate on the "episode_number" field.
func EpisodeNumberGTE(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldEpisodeNumber, v))
}

// EpisodeNumberLT applies the LT predicate on the "episode_number" field.
func EpisodeNumberLT(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldEpisodeNumber, v))
}

// EpisodeNumberLTE applies the LTE predicate on the "episode_number" field.
func EpisodeNumberLTE(v int) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldEpisodeNumber, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasAnime applies the HasEdge predicate on the "anime" edge.
func HasAnime() predicate.Schedule {
	return predicate.Schedule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AnimeTable, AnimeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAnimeWith applies the HasEdge predicate on the "anime" edge with a given conditions (other predicates).
func HasAnimeWith(preds ...predicate.Anime) predicate.Schedule {
	return predicate.Schedule(func(s *sql.Selector) {
		step := newAnimeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Schedule) predicate.Schedule {
	return predicate.Schedule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Schedule) predicate.Schedule {
	return predicate.Schedule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Schedule) predicate.Schedule {
	return predicate.Schedule(sql.NotPredicates(p))
}
