export interface Anime {
  id: string
  title: string
  poster: string
  synopsis: string
  genres: string[]
  status: 'Ongoing' | 'Finished'
  year: number
  type: 'TV' | 'Movie' | 'OVA' | 'Special'
  studio: string
  episodes: number
  rating: number
}

export const genres = [
  'Action',
  'Adventure',
  'Comedy',
  'Drama',
  'Fantasy',
  'Horror',
  'Isekai',
  'Mecha',
  'Mystery',
  'Psychological',
  'Romance',
  'Sci-Fi',
  'Seinen',
  'Shounen',
  'Slice of Life',
  'Sports',
  'Supernatural',
  'Thriller',
] as const

export const studios = [
  'MAPPA',
  'Ufotable',
  'Wit Studio',
  'Studio Ghibli',
  'Bones',
  'A-1 Pictures',
  'Kyoto Animation',
  'Madhouse',
  'Production I.G',
  'Toei Animation',
  'Sunrise',
  'CloverWorks',
] as const

export const types = ['TV', 'Movie', 'OVA', 'Special'] as const
export const statuses = ['ongoing', 'released'] as const

export const animeData: Anime[] = [
  {
    id: '1',
    title: 'Jujutsu Kaisen',
    poster: 'https://cdn.myanimelist.net/images/anime/1171/109222l.jpg',
    synopsis: 'A boy swallows a cursed talisman and becomes host to an evil spirit. He joins a secret society to fight curses while searching for the remaining talismans.',
    genres: ['Action', 'Supernatural', 'Shounen'],
    status: 'Ongoing',
    year: 2020,
    type: 'TV',
    studio: 'MAPPA',
    episodes: 47,
    rating: 8.7,
  },
  {
    id: '2',
    title: 'Attack on Titan',
    poster: 'https://cdn.myanimelist.net/images/anime/10/47347l.jpg',
    synopsis: 'Humanity lives inside cities surrounded by enormous walls due to the Titans, gigantic humanoid beings who devour humans seemingly without reason.',
    genres: ['Action', 'Drama', 'Fantasy'],
    status: 'Finished',
    year: 2013,
    type: 'TV',
    studio: 'Wit Studio',
    episodes: 87,
    rating: 9.1,
  },
  {
    id: '3',
    title: 'Demon Slayer',
    poster: 'https://cdn.myanimelist.net/images/anime/1286/99889l.jpg',
    synopsis: 'A family is attacked by demons and only two members survive. Tanjiro embarks on a journey to become a demon slayer and find a cure for his sister.',
    genres: ['Action', 'Supernatural', 'Shounen'],
    status: 'Ongoing',
    year: 2019,
    type: 'TV',
    studio: 'Ufotable',
    episodes: 55,
    rating: 8.9,
  },
  {
    id: '4',
    title: 'Spy x Family',
    poster: 'https://cdn.myanimelist.net/images/anime/1441/122795l.jpg',
    synopsis: 'A spy on an undercover mission assembles a fake family to execute his mission, not realizing his wife is an assassin and daughter a telepath.',
    genres: ['Action', 'Comedy', 'Slice of Life'],
    status: 'Ongoing',
    year: 2022,
    type: 'TV',
    studio: 'CloverWorks',
    episodes: 37,
    rating: 8.6,
  },
  {
    id: '5',
    title: 'Chainsaw Man',
    poster: 'https://cdn.myanimelist.net/images/anime/1806/126216l.jpg',
    synopsis: 'Denji is a young man trapped in poverty, working as a Devil Hunter to pay off his deceased father\'s debt to the yakuza.',
    genres: ['Action', 'Horror', 'Supernatural'],
    status: 'Ongoing',
    year: 2022,
    type: 'TV',
    studio: 'MAPPA',
    episodes: 12,
    rating: 8.5,
  },
  {
    id: '6',
    title: 'Your Name',
    poster: 'https://cdn.myanimelist.net/images/anime/5/87048l.jpg',
    synopsis: 'Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?',
    genres: ['Romance', 'Drama', 'Supernatural'],
    status: 'Finished',
    year: 2016,
    type: 'Movie',
    studio: 'CoMix Wave Films',
    episodes: 1,
    rating: 9.0,
  },
  {
    id: '7',
    title: 'Solo Leveling',
    poster: 'https://cdn.myanimelist.net/images/anime/1024/138696l.jpg',
    synopsis: 'In a world where hunters battle deadly monsters, Sung Jin-woo, the weakest of all, discovers a hidden dungeon that grants him the power to level up.',
    genres: ['Action', 'Fantasy', 'Adventure'],
    status: 'Ongoing',
    year: 2024,
    type: 'TV',
    studio: 'A-1 Pictures',
    episodes: 12,
    rating: 8.8,
  },
  {
    id: '8',
    title: 'One Punch Man',
    poster: 'https://cdn.myanimelist.net/images/anime/12/76049l.jpg',
    synopsis: 'Saitama is a hero who only became a hero for fun. After three years of training, he becomes strong enough to defeat any enemy with a single punch.',
    genres: ['Action', 'Comedy', 'Seinen'],
    status: 'Ongoing',
    year: 2015,
    type: 'TV',
    studio: 'Madhouse',
    episodes: 24,
    rating: 8.5,
  },
  {
    id: '9',
    title: 'Death Note',
    poster: 'https://cdn.myanimelist.net/images/anime/9/9453l.jpg',
    synopsis: 'A high school student discovers a supernatural notebook that allows him to kill anyone by writing the victim\'s name while picturing their face.',
    genres: ['Mystery', 'Psychological', 'Thriller'],
    status: 'Finished',
    year: 2006,
    type: 'TV',
    studio: 'Madhouse',
    episodes: 37,
    rating: 9.0,
  },
  {
    id: '10',
    title: 'Frieren: Beyond Journey\'s End',
    poster: 'https://cdn.myanimelist.net/images/anime/1015/138006l.jpg',
    synopsis: 'The story follows Frieren, an elf mage, who embarks on a journey to understand humanity after the death of her companions.',
    genres: ['Adventure', 'Drama', 'Fantasy'],
    status: 'Ongoing',
    year: 2023,
    type: 'TV',
    studio: 'Madhouse',
    episodes: 28,
    rating: 9.2,
  },
  {
    id: '11',
    title: 'My Hero Academia',
    poster: 'https://cdn.myanimelist.net/images/anime/10/78745l.jpg',
    synopsis: 'In a world where most humans have superpowers, a powerless boy dreams of becoming a hero and enrolls in a prestigious hero academy.',
    genres: ['Action', 'Shounen', 'Supernatural'],
    status: 'Ongoing',
    year: 2016,
    type: 'TV',
    studio: 'Bones',
    episodes: 138,
    rating: 8.0,
  },
  {
    id: '12',
    title: 'Violet Evergarden',
    poster: 'https://cdn.myanimelist.net/images/anime/1795/95088l.jpg',
    synopsis: 'A former soldier begins working as a letter writer to understand the final words her commander told her: "I love you."',
    genres: ['Drama', 'Slice of Life', 'Fantasy'],
    status: 'Finished',
    year: 2018,
    type: 'TV',
    studio: 'Kyoto Animation',
    episodes: 13,
    rating: 8.7,
  },
  {
    id: '13',
    title: 'Steins;Gate',
    poster: 'https://cdn.myanimelist.net/images/anime/5/73199l.jpg',
    synopsis: 'A self-proclaimed mad scientist accidentally discovers time travel and must deal with the consequences of altering the past.',
    genres: ['Sci-Fi', 'Thriller', 'Drama'],
    status: 'Finished',
    year: 2011,
    type: 'TV',
    studio: 'Production I.G',
    episodes: 24,
    rating: 9.1,
  },
  {
    id: '14',
    title: 'Mob Psycho 100',
    poster: 'https://cdn.myanimelist.net/images/anime/8/80356l.jpg',
    synopsis: 'A psychic middle school boy tries to live a normal life and keep his growing powers under control, even though he constantly gets into trouble.',
    genres: ['Action', 'Comedy', 'Supernatural'],
    status: 'Finished',
    year: 2016,
    type: 'TV',
    studio: 'Bones',
    episodes: 37,
    rating: 8.6,
  },
  {
    id: '15',
    title: 'Spirited Away',
    poster: 'https://cdn.myanimelist.net/images/anime/6/79597l.jpg',
    synopsis: 'A young girl becomes trapped in a strange spirit world and must work at a bathhouse to free herself and her parents.',
    genres: ['Adventure', 'Fantasy', 'Supernatural'],
    status: 'Finished',
    year: 2001,
    type: 'Movie',
    studio: 'Studio Ghibli',
    episodes: 1,
    rating: 9.3,
  },
  {
    id: '16',
    title: 'Fullmetal Alchemist: Brotherhood',
    poster: 'https://cdn.myanimelist.net/images/anime/1208/94745l.jpg',
    synopsis: 'Two brothers search for a Philosopher\'s Stone after an attempt to revive their deceased mother goes awry and leaves them in damaged physical forms.',
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy'],
    status: 'Finished',
    year: 2009,
    type: 'TV',
    studio: 'Bones',
    episodes: 64,
    rating: 9.2,
  },
  {
    id: '17',
    title: 'Vinland Saga',
    poster: 'https://cdn.myanimelist.net/images/anime/1500/103005l.jpg',
    synopsis: 'Thorfinn pursues a journey with his father\'s killer in order to take revenge and end the cycle of hatred and war.',
    genres: ['Action', 'Adventure', 'Drama', 'Seinen'],
    status: 'Ongoing',
    year: 2019,
    type: 'TV',
    studio: 'MAPPA',
    episodes: 48,
    rating: 8.8,
  },
  {
    id: '18',
    title: 'Oshi no Ko',
    poster: 'https://cdn.myanimelist.net/images/anime/1812/134736l.jpg',
    synopsis: 'A doctor who is a fan of an idol is reborn as one of her children and must navigate the dark side of the entertainment industry.',
    genres: ['Drama', 'Supernatural', 'Mystery'],
    status: 'Ongoing',
    year: 2023,
    type: 'TV',
    studio: 'Doga Kobo',
    episodes: 11,
    rating: 8.9,
  },
  {
    id: '19',
    title: 'Bocchi the Rock!',
    poster: 'https://cdn.myanimelist.net/images/anime/1448/127956l.jpg',
    synopsis: 'A lonely high school girl learns to play guitar and joins a band, hoping to make friends and overcome her social anxiety.',
    genres: ['Comedy', 'Slice of Life', 'Music'],
    status: 'Finished',
    year: 2022,
    type: 'TV',
    studio: 'CloverWorks',
    episodes: 12,
    rating: 8.8,
  },
  {
    id: '20',
    title: 'Blue Lock',
    poster: 'https://cdn.myanimelist.net/images/anime/1258/126929l.jpg',
    synopsis: 'Three hundred of Japan\'s best and brightest young strikers are pitted against each other in a competition to create the world\'s greatest egotist striker.',
    genres: ['Sports', 'Shounen'],
    status: 'Ongoing',
    year: 2022,
    type: 'TV',
    studio: '8bit',
    episodes: 24,
    rating: 8.4,
  },
]
